
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flight_booking
    username: root
    password: b6592a2cA*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: flight_booking


  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    default-schema: flight_booking
    enabled: true
    database-change-log-table: LOG_TABLE_DBLOG
    database-change-log-lock-table: LOCK_TABLE_DBLOCK
  mail:
    host: smtp.gmail.com
    port: 587
    username: fahruz.amirov@gmail.com
    password: yptvivolrfhvfwlq
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      springframework:
        security=DEBUG:

